In [13]:
import numpy as np
a = np.int8(25)
print(type(a))


np.iinfo(np.int64)

<class 'numpy.int8'>


iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [17]:
b = np.uint8(124)
print(b)

print(type(b))

np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

Массивы

In [3]:
import numpy as np

arr = np.array([1,5,2,9,10])

print(type(arr))

<class 'numpy.ndarray'>


In [38]:
nd_arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76],
], dtype=np.int8) #задаём тип массива

nd_arr.dtype

dtype('int8')

In [41]:
arr = np.array([1,5,2,9,10], dtype=np.int8)

arr[2] = 2000
arr


array([  1,   5, -48,   9,  10], dtype=int8)

In [42]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [43]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [45]:
arr[2] = 'test'

ValueError: invalid literal for int() with base 10: 'test'

In [48]:
arriva = np.array([345234, 876362.12, 0, -1000, 99999999])
arriva.dtype

dtype('float64')

In [4]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [51]:

# узнать размерность массива .ndim
nd_arr.ndim

2

In [52]:
#Узнать общее число элементов в массиве можно с помощью .size:
nd_arr.size

9

In [5]:
# Форма или структура массива хранится в атрибуте .shape
nd_arr.shape

(3, 3)

In [6]:
# сколько «весит» каждый элемент массива в байтах позволяет .itemsize
nd_arr.itemsize

2

In [7]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [9]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является arange.
 Она аналогична встроенной функции range, но обладает рядом особенностей.
  Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [12]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [13]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
endpoint — включён или исключён конец диапазона (по умолчанию включён);
retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

In [15]:
arr = np.linspace(1,2,10)#массив между 1 и 2 из 10 чисел
arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [16]:
arr = np.linspace(1,2,10, endpoint = False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [17]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)#узнаем шаг
print(step)

0.1111111111111111


In [18]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


In [22]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45
