In [1]:
import numpy as np
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6,13])
vec1 + vec2


array([14. , 10. , 10.6, 15.5])

In [4]:
import numpy as np
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6,13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [5]:
import numpy as np
vec1 = np.array([2,4,7,2.5])
vec2 = np.array([12,6,3.6])#второй вектор на 1 элемент меньше
vec1 * vec2

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [8]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])


vec1 <= 26

array([ True,  True,  True,  True])

In [9]:
vec = np.array([3, 4])
lenght = np.sqrt(np.sum(vec**2)) #длина вектора сложно
print(lenght)

5.0


In [10]:
vec = np.array([3, 4])
lenght = np.linalg.norm(vec)#длина вектора просто
print(lenght)

5.0


In [11]:
#расстояние между векторами
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1-vec2)**2))
distance

12.206555615733702

In [13]:
#расстояние между векторами просто
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [14]:
# скалярное произведение
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1*vec2)
scalar_product


250.0

In [15]:
# скалярное произведение
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [16]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y) # скалярное произведение равное 0, означает что векторы перпендикулярны

0

In [23]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

len_sum_a_b = np.linalg.norm(a) + np.linalg.norm(b)
len_sum_b_c = np.linalg.norm(b) + np.linalg.norm(c)
len_sum_a_c = np.linalg.norm(a) + np.linalg.norm(c)

sum_a_b = a+b
sum_b_c = b+c
sum_a_c = a+c

len_a_b = np.linalg.norm(sum_a_b)
len_b_c = np.linalg.norm(sum_b_c)
len_a_c = np.linalg.norm(sum_a_c)

print(len_sum_a_b==len_a_b,len_sum_b_c==len_b_c,len_sum_a_c==len_a_c)


False False True


In [ ]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

distance = np.linalg.norm(a - b)